### PR TITLE
Custom filter operators for queries

### LINKED ISSUE #64: Add dropdown for operators in query
Currently implicitly `==`, should be able to specify: 
- `==`
- `!=`
- `<`
- `>`
- `<=`
- `>=`

### PR DESCRIPTION
**Pull request by MichaelGoodale**
This would fix #64 . Currently the frontend works(although it needs set defaults, and to prevent people from choosing operators where it doesn't make sense, e.g. using `<=` on strings). 

The backend I don't think works yet, I might be misunderstanding how `q.filter` works. @mmcauliffe  could you take a look at this?

### CODE REVIEW

**Comment by MichaelGoodale** [comment]
@mmcauliffe Is there any way to check if a property accepts string or numerical input?

**Comment by mmcauliffe** [comment]
In the JS?  There's propertyTypes (https://github.com/MontrealCorpusTools/polyglot-server/blob/master/pgdb/static/pgdb/query/query.js#L143), which will have the value of '' for strings and 0 for numerical properties.

**Comment by msonderegger** [comment]
Wow!

**Comment by msonderegger** [comment]
could you update -- what's going on with this PR?

**Comment by MichaelGoodale** [comment]
So, I think it makes sense to merge this in now, with only the autocomplete and not the 'in/not in' checklist just because I don't think there's time for me to finish that aspect of the PR before leaving. Otherwise the autocomplete+custom filters should work. I also think it makes sense to merge it in now before the query model/page get too wildly different.

**Comment by msonderegger** [comment]
OK, great.  @mmcauliffe ?

**Pull request merged**
